#!/usr/bin/env bash
# JDI
sudo apt-get update -y;
sudo apt-get install -y haproxy;

cat ./haproxy.cfg | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart;
