#!/usr/bin/env bash
# JDI
sudo apt-get update;
sudo apt-get install -y nginx;

echo "Holberton School" | sudo tee /var/www/html/index.html;
# sudo cp ./1-nginx.conf /etc/nginx/sites-enabled/default;

sudo service nginx restart;
