#!/usr/bin/env bash
# JDI
sudo apt-get update -y;
sudo apt-get install -y nginx;
sudo apt-get install -y ufw;

sudo ufw enable;
sudo ufw allow 'Nginx HTTP';
sudo ufw allow 'OpenSSH';
sudo service nginx restart;

echo "Holberton School" | sudo tee /var/www/html/index.html;
# sudo cp ./1-nginx.conf /etc/nginx/nginx.conf;

sudo service nginx restart;
