#!/usr/bin/env bash
# JDI
sudo apt-get update;
sudo apt-get install -y nginx;
sudo apt-get install -y ufw;

sudo ufw enable;
sudo ufw allow 'Nginx HTTP';
sudo ufw allow 'OpenSSH';

sudo cp ./nginx-2.config /etc/nginx/sites-available/default;

sudo service nginx restart;
