#!/usr/bin/env bash
# JDI
sudo apt-get update;
sudo apt-get install -y nginx;
sudo apt-get install -y ufw;

sudo ufw enable;
sudo ufw allow 'Nginx HTTP';
sudo ufw allow 'OpenSSH';

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html;

# sudo cp ./nginx-4.conf /etc/nginx/sites-available/default;
SERVER_CONFIG="server {
    listen 80 default_server;
    server_name _;
    error_page 404 /404.html;

    location / {
        root https://devark28.github.io/alu-responsive-resume/;
        # index index.html;
        return 'Holberton School';
    };

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        internal;
    };

    # root /var/www/html/;
    location /404.html {
        return \"Ceci n'est pas une page\";
        internal;
    }
}";

echo -e "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-available/default;

sudo service nginx restart;
